# Generated by Django 2.1.2 on 2018-10-25 15:42

from django.db import migrations, models
import pendulum
import timers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', timers.models.DateTimeField(default=pendulum.now)),
                ('stop', timers.models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete='CASCADE', to='projects.Project')),
            ],
        ),
    ]
