# Generated by Django 2.1.2 on 2018-10-25 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('timers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timer',
            unique_together={('project', 'start')},
        ),
    ]
